global.expect = require('expect.js');
global.fidola = require('../lib/fidola.js');
require('./spec/Sequence.spec.js');
require('./spec/datastructure/BinaryHeap.spec.js');
require('./spec/datastructure/BinarySearchTree.spec.js');
require('./spec/datastructure/CartesianTree.spec.js');
require('./spec/datastructure/RedBlackTree.spec.js');
require('./spec/datastructure/LinkedList.spec.js');
require('./spec/datastructure/ImmutableArray.js');
require('./spec/NumberTheory.spec.js');
require('./spec/MultiPrecision.spec.js');
require('./spec/Numeric.spec.js');
